//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANTARA_Marketplace.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string RatingID { get; set; }
        public string ProductID { get; set; }
        public string StorageID { get; set; }
        public string UserID { get; set; }
        public double RatingValue { get; set; }
        public string RatingDescription { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Storage Storage { get; set; }
        public virtual User User { get; set; }
    }
}
